global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vagechain-node'
    static_configs:
      - targets: ['localhost:8080'] # Default RPC port for validator 1
  - job_name: 'vagechain-network'
    static_configs:
      - targets: ['localhost:8081', 'localhost:8082', 'localhost:8083']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
